### ISSUE TITLE
Error in line 74#

### ISSUE THREAD

**Issue by 8bit-token** [AlgoNetwork/Free-Woocommerce-Ethereum-Evm-Compatible-ERC20-BEP20-Token-Payment-Gateway#1]
When im using in my marketplace this payment method, i get this error

{"type":8,"message":"Undefined index: request","file":"\/***\/nft\/wp-content\/plugins\/Woocommerce-Ethereum-Evm-Compatible-ERC20-BEP20-Token-Payment-Gateway-main\/woocommerce-ethereum-evm-token-payment-gateway.php","line":74}

**Comment by marmisantos** [comment]
how to set #of tokens?
may i know how to set the price per live token ?
like be able to use coingecko or coinpaprika to track live coin prices

**Comment by AlgoNetwork** [comment]
it doesn't support NFT.
